### ISSUE TITLE
[fix] 기본 식물 위치 추가

### ISSUE THREAD

**Issue by dompoo** [dnd-side-project/dnd-11th-8-backend#42]
### 수정할 기능 설명
- 기존에는 회원가입시 location이 하나도 제공되지 않았습니다.
- 이제부터는 기본적으로 3개의 location을 제공합니다.

### 수정 방법
- 회원가입 로직에 user 엔티티에 다음 3개의 장소를 기본적으로 추가/매핑
  - 거실
  - 침실
  - 테라스

**Comment by stophwan** [comment]
이거 목요일 회의 한번 하고 결정해도 될것 같아요
